# Generated by Django 3.1.1 on 2020-11-22 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentinfo_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='AuthenticationKey',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
