# Generated by Django 3.1.1 on 2020-11-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtext',
            name='online_text_expand_contest',
            field=models.TextField(default='cc'),
        ),
        migrations.AddField(
            model_name='learningtext',
            name='text_question',
            field=models.TextField(default='cc'),
        ),
        migrations.AddField(
            model_name='learningtext',
            name='text_question_answer',
            field=models.TextField(default='cc'),
        ),
    ]
