# Generated by Django 3.1.1 on 2020-11-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinelearning', '0002_auto_20201123_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtext',
            name='text_question',
        ),
        migrations.RemoveField(
            model_name='learningtext',
            name='text_question_answer',
        ),
        migrations.AlterField(
            model_name='learningtext',
            name='online_text_expand_contest',
            field=models.TextField(default=models.TextField()),
        ),
        migrations.CreateModel(
            name='Quizgenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField(default='no text_question')),
                ('text_question_answer', models.TextField(default='no text_question_answer')),
                ('text_question_type', models.TextField(default='cloze')),
                ('textcontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinelearning.learningtext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
