# Generated by Django 3.1.1 on 2020-11-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0002_auto_20201122_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtext',
            name='online_text_expand_contest',
            field=models.TextField(default='no online_text_expand_contest'),
        ),
        migrations.AlterField(
            model_name='learningtext',
            name='text_question',
            field=models.TextField(default='no text_question'),
        ),
        migrations.AlterField(
            model_name='learningtext',
            name='text_question_answer',
            field=models.TextField(default='no text_question_answer'),
        ),
    ]
