# Generated by Django 3.1.1 on 2020-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0003_auto_20201126_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtext',
            name='online_text_title',
            field=models.TextField(default='title null'),
        ),
        migrations.AddField(
            model_name='quizgenerator',
            name='text_key_word',
            field=models.TextField(default='null'),
        ),
    ]
