# Generated by Django 3.1.1 on 2020-12-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0004_auto_20201203_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtext',
            name='online_text_language',
            field=models.TextField(default='en'),
        ),
    ]
