# Generated by Django 3.1.1 on 2020-12-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinelearning', '0005_learningtext_online_text_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtext',
            name='slug',
            field=models.SlugField(default='-'),
        ),
        migrations.CreateModel(
            name='LearningComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinelearning.learningtext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
