# Generated by Django 3.1.1 on 2020-12-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0006_auto_20201205_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcomment',
            old_name='text',
            new_name='ontext',
        ),
        migrations.RenameField(
            model_name='learningcomment',
            old_name='time',
            new_name='texttime',
        ),
    ]
