# Generated by Django 3.1.1 on 2020-12-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0007_auto_20201205_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningComment',
        ),
    ]
