# Generated by Django 3.1.1 on 2020-12-05 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0008_delete_learningcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningtextLearningnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnnote', models.TextField()),
                ('learnnote_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('onlinetext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinelearning.learningtext')),
            ],
        ),
    ]
