# Generated by Django 3.1.1 on 2020-12-05 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelearning', '0010_quizgenerator_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgenerator',
            name='text_question_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
